# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'log_tools/version'

Gem::Specification.new do |s|
    s.name = "log_tools"
    s.version = LogTools::VERSION
    s.authors = ["Alexander Duda", "Sylvain Joyeux"]
    s.email = "alexander.duda@dfki.de"
    s.summary = "Manipulation of log files generated by pocolog"
    s.description = ""
    s.homepage = "http://rock-robotics.org"
    s.licenses = ["LGPLv2+"]

    s.require_paths = ["lib"]
    s.extensions = []
    s.extra_rdoc_files = ["README.md"]
    s.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }

    s.add_runtime_dependency "utilrb", ">= 3.0.0.a"
    s.add_development_dependency "flexmock", ">= 2.0.0"
    s.add_development_dependency "minitest", ">= 5.0", "~> 5.0"
    s.add_development_dependency "coveralls"
end
